name: linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'  

      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/pip install -r requirements.txt

      - name: Run flake8 (Linting)
        run: |
          venv/bin/flake8 . --ignore E501,W503

      - name: Run pytest (Unit Tests)
        run: |
          venv/bin/pytest --tb=short --disable-warnings

